# Generated by Django 2.2.24 on 2022-12-10 22:49

from django.db import migrations


def set_new_building_state_by_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    LOWEST_YEAR_FOR_NEW_BUILDING = 2015

    Flat.objects.filter(
        construction_year__gte=LOWEST_YEAR_FOR_NEW_BUILDING).update(
        new_building=True)
    Flat.objects.filter(
        construction_year__lt=LOWEST_YEAR_FOR_NEW_BUILDING).update(
        new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building_state_by_year)
    ]
