# Generated by Django 2.2.24 on 2022-12-10 22:49

from django.db import migrations


def set_new_building_state_by_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    LOWEST_YEAR_FOR_NEW_BUILDING = 2015
    for flat in Flat.objects.all():
        if flat.construction_year >= LOWEST_YEAR_FOR_NEW_BUILDING:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building_state_by_year)
    ]
