# Generated by Django 2.2.24 on 2022-12-20 22:27

from django.db import migrations

import phonenumbers


def normalize_owner_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if not (phonenumbers.is_valid_number(pure_phone) and
                phonenumbers.is_valid_number_for_region(pure_phone, 'RU')):
            pure_phone = None
        flat.owner_pure_phone = pure_phone
        flat.save()




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20221221_0123'),
    ]

    operations = [
        migrations.RunPython(normalize_owner_phonenumbers)
    ]
