# Generated by Django 2.2.24 on 2023-01-11 19:51

from django.db import migrations


def add_flats_to_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    for flat_owner in Owner.objects.all():
        flats = Flat.objects.filter(
            owner=flat_owner.name,
            owners_phonenumber=flat_owner.phonenumber)
        flat_owner.flats.add(*flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20230111_2251'),
    ]

    operations = [
        migrations.RunPython(add_flats_to_owners)
    ]
